version: "3.9"


services:
  babelfish_compass:
    build:
      context: .
      dockerfile: ./babelfishcompass/Dockerfile
    container_name: babelfish_compass
    volumes:
      - ./babelfishcompass/ata:/data
      - ./babelfishcompass/data:/root/BabelfishCompassReports
      - ./babelfishcompass/data:/tmp/

  # pgloader:
  #   image: dimitri/pgloader:latest
  #   container_name: pgloader
  #   volumes:
  #     - ./pgloader:/pgloader
  #     - ./data:/data
  #     - ./tdsconf:/etc/freetds
  #   command: tail -f /dev/null  # Keeps the container running
  #   restart: always  # Ensures the container restarts if it stops

  pgloader:
    build: 
      context: .
      dockerfile: ./pgloader/Dockerfile
    container_name: pgloader
    volumes:
      - ./pgloader/data:/pgloader
      - ./pgloader/tdsconf:/etc/freetds
    restart: always
    env_file:
      - ./pgloader/.env